title: Right join data
description: >-
  Writing down ideas from my work with data
github_username:  ilmari-aalto

theme: minima
show_excerpts: true
plugins:
  - jekyll-feed
  - jekyll-seo-tag

google_analytics: UA-54965810-2
